language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_script:
   - composer install
script: "composer test --verbose --coverage-clover ./build/logs/clover.xml"
after_script:
  - php vendor/bin/coveralls -v
