language: php
php:
  - 5.6
  - 5.5
before_install:
  - composer self-update
install:
  - composer clear-cache
  - composer install --prefer-source
script:
  - composer test --verbose
notifications:
  email: vmalinovskiy@callfire.com
